runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: process.env.APP_ID
  MASTER_KEY: process.env.MASTER_KEY
  SERVER_URL: process.env.SERVER_URL
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
